Qitmeer/qng

- services/mempool/mempool.go
> BUG:The error of verifying vm tx fee

- core/json/blocktemplate.go
- core/merkle/merkle.go
- core/types/blocktemplate.go
- engine/txscript/consensus.go
- script/cli.sh
- services/miner/README.md
- services/miner/api.go
- services/miner/gbtworker.go
- services/miner/miner.go
- services/miner/msg.go
- services/miner/remoteworker.go
- services/mining/mining.go
- services/mining/newblocktemplate.go
https://github.com/lochjin/qng/blob/main/services/miner/README.md#how-to-use-extra-nonce-by-coinbaseflagsdynamic-in-remote-gbt-
> RemoteWorker support CoinbaseFlagsDynamic

- cmd/miner/common/config.go
- cmd/miner/core/stratum.go
> fix issue 48

- consensus/vmi.go
- core/blockchain/blockchain.go
- core/blockchain/validate.go
- core/blockchain/validate_test.go
- meerevm/chain/meerchain.go
- meerevm/evm/vm.go
- services/mining/newblocktemplate.go
- vm/consensus/chainvm.go
- vm/service.go
> Revert "Consensus:meervm state root upload to blockchain"

- .github/workflows/go.yml
- basetest/base_test.go
- meerevm/chain/genesis_check.go
> base check

- meerevm/chain/ethchain.go
> [Fix #220]Force-load the tracer engines

- README.md
Tidy and add a bit more details of README, for building qng and using qx.
> Tidy and add a bit more details of README

- services/miner/cpuworker.go
- services/miner/gbtworker.go
- services/miner/miner.go
- services/miner/remoteworker.go
> Revert "recreate BlockTemplate when transactions is empty except coinbase tx"

- p2p/synch/peersync.go
the line is printed out rampantly
> p2p: reduce log level to trace

- qx/handle_tx.go
> fix txdecode panic

- cmd/qx/README.md
- cmd/qx/qx.go
> spelling error in qx code

- qx/handle_tx.go
- qx/scriptbasetypes/base.go
> special cross type

- common/marshal/marshal.go
- core/json/tx.go
> required to display  the `coinid` for the `vout` 

- go.mod
- go.sum
https://github.com/Qitmeer/qng/issues/300
> go-ethereum v1.10.21-q.4

- go.mod
- go.sum
> update to go-ethereum v1.10.26-q.2

- go.mod
- meerdag/blocktransf.go
- meerdag/dagsync.go
The transmission efficiency of the whole network will be greatly improved
> Optimizing block synchronization path search algorithm

- meerevm/README.md
- meerevm/cmd/cmds.go
- meerevm/eth/chain.go
Situation: Database has receipts with a legacy format.
> BUG:database error about legacy format in QitSubnet

- p2p/api.go
- p2p/service.go
- script/cli.sh
`--modules=p2p`
```shell 
curl -u test:test -k -X POST  -k https://127.0.0.1:18132/  \
-H 'content-type: application/json' \
-d '{"jsonrpc":"2.0","method":"p2p_reloadPeers","params":[],"id":1}'
```
```shell
$ ./script/cli.sh -p 18132 reloadpeers
```
> add reload peers rpc

- meerdag/meerdag.go
- script/cli.sh
- services/miner/api.go
- services/miner/gbtworker.go
- services/miner/miner.go
```bash
./cli.sh -p 18131 miningstats
```
> mining stats

- cmd/qng/blockchain_cmds.go
- common/util/file.go
./qng -A=. blockchain upgrade --aidmode
> Optimize out of memory for upgrade command

- p2p/synch/chainstate.go
Function changed to manual: ./cli.sh consistency
> Remove state root check for chainstate msg

- meerdag/dbhelper.go
https://github.com/Qitmeer/qng/security/code-scanning/5
> BUG:Incorrect conversion between integer types

- Makefile
This reverts commit 8f8d7a5b6374951d6243091eea81ec0af823d030.
> Revert "make: disable the cgo build by default"

- cmd/miner/symbols/lib/robot.go
> pick the PR 550 to the dev/1.0 branch

- core/blockchain/api.go
- core/blockchain/blockchain.go
- core/blockchain/meerchain.go
- core/blockchain/process.go
- core/types/block.go
- meerdag/meerdag.go
> BUG:Inconsistent calculation of stateroot results in inability to block sync

- services/mempool/mempool.go
- services/miner/miner.go
see #465 BUG:mempool notify error
> cherrypick PR #465 into dev/1.0 branch

- config/config.go
- consensus/forks/emptyblockfork.go
- core/blockchain/blockchain.go
- core/blockchain/process.go
- core/json/node.go
- meerdag/meerdag.go
- meerdag/tips.go
- node/api.go
- p2p/synch/getblockdatas.go
- p2p/synch/inventory.go
- params/params_privnet.go
- services/common/flags.go
- services/miner/miner.go
> Performance optimization of parallel block generation between multiple nodes
